title: EmoRemap
description: INTRA-CLASS INTENSITY CONTROL FOR EMOTION TRANSFER SPEECH SYNTHESIS USING REMAPPING

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/lemon-ustc/EmoRemap-demo
